### ISSUE TITLE
VIEW: Add date adoptable to 90 day eligible view: http://localhost:3000/#!/admin/eligibility

### ISSUE THREAD

**Issue by drteresavasquez** [HorseHaven-ManeFrame/maneframe#1]
VIEW: Add date adoptable to 90 day eligible view: http://localhost:3000/#!/admin/eligibility

**Comment by tylerb33** [comment]
NOTES from talk with Teresa: After you you click on the 'available for ownership' button on dashboard, display the actual date available for adoption on the view.
